name: Create Branch on Merge

on:
  push:
    branches: [main]
#
jobs:
  create-branch-on-merge:
    name: Create Branch on Merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # 0 depth required for successful auto PR merge process to avoid unrelated history error
          token: ${{ github.token }}

      - name: Configure Git User
        run:  |
          git config user.email "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git config user.name "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

      - name: Get Next Sprint Branch
        id: get_next_sprint_branch
        uses: azure/powershell@v1.4.0
        with:
          failOnStandardError: true
          azPSVersion: "latest"
          inlineScript: ./scripts/Get-NextSprintBranch.ps1
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Fix Non-Executable Bash Scripts
        shell: bash
        run: find ./scripts/ -type f -iname '*.sh' -not -executable -exec chmod +x {} \;

      - name:  Setup Next Sprint Branch
        shell: bash
        run: ./scripts/Set-NextSprintBranch.sh
        env:
          GH_TOKEN: ${{ github.token }}
          NEXT_SPRINT_BRANCH_NAME: ${{ steps.get_next_sprint_branch.outputs.SPRINT_BRANCH_NAME }}
